# This workflow runs sphinx and publishes the output with Github pages

name: pages-build-sphinx

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies via pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run sphinx
      run: make html

    - name: Deploy to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
